management:
  port: 5567
server:
  port: 5566

keycloak:
  public-client: true
  auth-server-url: http://localhost:8080/auth
  realm: realm
  resource: zuul-server
  # ssl-required: external
  securityConstraints:
  - authRoles:
    - user
    securityCollections:
    - name: user-haha
      patterns:
      - /ms-content-sample/articles
      - /ms-consumer-sample/articles