server:
  port: 8010


keycloak:
  auth-server-url: http://localhost:8080/auth
  realm: realm
  resource: ms-consumer-sample
  securityConstraints:
  - authRoles:
    - user
    securityCollections:
    - name: user-haha
      patterns:
      - /articles
  public-client: true