
keycloak:
  auth-server-url: http://localhost:8080/auth
  realm: realm
  resource: ms-content-sample
  # ssl-required: external
  securityConstraints:
  - authRoles:
    - user
    securityCollections:
    - name: user-haha
      patterns:
      - /articles
  public-client: true
server:
  port: 8081