spring:
  profiles:
    active: ${PROFILE:dev}
server:
  port: 8761
---
spring:
  profiles: dev
eureka:
  client:
    useHeadlessService: false
    service-url:
      defaultZone: http://localhost:8761/eureka/
    # 是否注册到其他eureka server节点，单机模式下设为FALSE
    register-with-eureka: false
    # 是否从其他eureka server节点获取服务信息，单机模式下设为FALSE
    fetch-registry: false
  instance:
    # renew频率，向Eureka服务发送renew信息，默认30秒
    # 服务失效时间，Eureka多长时间没收到服务的renew操作，就剔除该服务，默认90秒
    lease-expiration-duration-in-seconds: 15
  server:
    # 开发环境关闭eureka自我保护模式
    enable-self-preservation: false
